import type { Metadata } from "next";
import "./globals.scss";

import { Pacifico } from "next/font/google";
import { Lexend } from "next/font/google";

const pacifico = Pacifico({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-pacifico",
});

const lexend = Lexend({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-lexend",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
    <body className={`${pacifico.variable} ${lexend.variable}`}>
      {children}
    </body>
  </html>
  );
}
